name: 스프링 앱 배포

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: JDK 설정
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: 빌드
        run: ./mvnw package -DskipTests
        
      - name: Google Cloud 인증
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: gcloud 설정
        uses: google-github-actions/setup-gcloud@v1
        
      - name: JAR 파일 복사 및 배포
        run: |
          gcloud compute scp target/*.jar ${{ secrets.GCE_INSTANCE }}:~/app.jar --zone=${{ secrets.GCE_ZONE }}
          gcloud compute ssh ${{ secrets.GCE_INSTANCE }} --zone=${{ secrets.GCE_ZONE }} --command="
            sudo systemctl stop spring-app || true
            sudo mv ~/app.jar /opt/spring-app/app.jar
            sudo systemctl start spring-app
          "
