name: 스프링 앱 배포
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: JDK 설정
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Gradle 빌드
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test
          
      - name: JAR 파일 확인
        run: |
          # 빌드된 JAR 파일 확인
          echo "빌드된 JAR 파일 목록:"
          find build/libs -type f -name "*.jar" -exec ls -la {} \;
          # JAR 파일 명확하게 지정
          echo "JAR_FILE=$(find build/libs -type f -name "*.jar" | head -1)" >> $GITHUB_ENV
        
      - name: Google Cloud 인증
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: gcloud 설정
        uses: google-github-actions/setup-gcloud@v1
        
      - name: SSH로 배포
        run: |
          # SSH 키를 설정
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          
          # JAR 파일을 VM으로 복사 (SCP 대신 gcloud를 이용한 SSH 명령으로 수행)
          echo "JAR 파일을 VM으로 전송 중..."
          cat ${{ env.JAR_FILE }} | gcloud compute ssh lecture2quiz@spring-app-instance --zone=${{ secrets.GCE_ZONE }} --ssh-key-file=private_key.pem -- "cat > /tmp/application.jar"
          
          # 디렉토리 설정 및 파일 이동
          echo "서비스 설정 중..."
          gcloud compute ssh lecture2quiz@spring-app-instance --zone=${{ secrets.GCE_ZONE }} --ssh-key-file=private_key.pem -- "
            sudo mkdir -p /opt/spring-app
            sudo cp /tmp/application.jar /opt/spring-app/
            sudo chown -R lecture2quiz:lecture2quiz /opt/spring-app
            
            # 서비스 파일이 없으면 생성
            if [ ! -f /etc/systemd/system/spring-app.service ]; then
              echo '[Unit]
              Description=Spring Boot Application
              After=network.target
              
              [Service]
              User=lecture2quiz
              Group=lecture2quiz
              WorkingDirectory=/opt/spring-app
              ExecStart=/usr/bin/java -jar /opt/spring-app/application.jar
              SuccessExitStatus=143
              Restart=always
              RestartSec=5
              
              [Install]
              WantedBy=multi-user.target' | sudo tee /etc/systemd/system/spring-app.service
              
              sudo systemctl daemon-reload
              sudo systemctl enable spring-app
            fi
            
            # 서비스 재시작
            sudo systemctl restart spring-app
            
            # 상태 확인
            sudo systemctl status spring-app
          "
          
          # 임시 키 파일 삭제
          rm private_key.pem
