name: 스프링 앱 배포
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: JDK 설정
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Gradle 캐시 설정
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
          
      - name: Gradle 빌드
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test
        
      - name: Google Cloud 인증
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: gcloud 설정
        uses: google-github-actions/setup-gcloud@v1
        
      - name: JAR 파일 복사 및 배포
        run: |
          # JAR 파일 원격 서버로 복사
          gcloud compute scp build/libs/*.jar ${{ secrets.GCE_INSTANCE }}:~/app.jar --zone=${{ secrets.GCE_ZONE }}
          
          # 디렉토리 생성 및 JAR 파일 이동
          gcloud compute ssh ${{ secrets.GCE_INSTANCE }} --zone=${{ secrets.GCE_ZONE }} --command="
            # 디렉토리 생성
            sudo mkdir -p /opt/spring-app/
            
            # JAR 파일 이동
            sudo mv ~/app.jar /opt/spring-app/app.jar
            
            # 권한 설정
            sudo chmod 755 /opt/spring-app/app.jar
            
            # Java로 애플리케이션 실행 (백그라운드에서)
            cd /opt/spring-app
            sudo nohup java -jar app.jar > app.log 2>&1 &
            
            echo '애플리케이션이 백그라운드에서 시작되었습니다.'
          "
