name: 스프링 앱 배포
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: JDK 설정
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Gradle 빌드
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test
          
      - name: JAR 파일 확인
        run: |
          # 빌드된 JAR 파일 확인
          echo "빌드된 JAR 파일 목록:"
          find build/libs -type f -name "*.jar" -exec ls -la {} \;
          # JAR 파일 명확하게 지정
          echo "JAR_FILE=$(find build/libs -type f -name "*.jar" | head -1)" >> $GITHUB_ENV
        
      - name: Google Cloud 인증
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: gcloud 설정
        uses: google-github-actions/setup-gcloud@v1
        
      - name: Deploy JAR to VM
        run: |
          # 홈 디렉토리로 직접 복사
          gcloud compute scp ${{ env.JAR_FILE }} spring-app-instance:/home/lecture2quiz/ --zone=${{ secrets.GCE_ZONE }}
          
          # 파일 이동 및 서비스 구성
          gcloud compute ssh spring-app-instance --zone=${{ secrets.GCE_ZONE }} --command="mkdir -p /home/lecture2quiz/app && mv /home/lecture2quiz/*.jar /home/lecture2quiz/app/application.jar"
